name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: Setup Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

  job2:
    name: List Docker Images
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: List Docker Images
        run: docker images

  job3:
    name: Check Docker Status
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Check Docker Status
        run: docker ps
